### ISSUE TITLE
"type" property in Chart.yaml disappears in the packaged chart

### ISSUE THREAD

**Issue by tashoyan** [microbean/helm-maven-plugin#54]
I have helm chat with the file Chart.yaml like this:
```yaml
apiVersion: v2
name: my-app
description: My App
version: 1.0.0-SNAPSHOT
type: application
appVersion: 1.0.0-SNAPSHOT
annotations:
  build-time: 2023-01-12T12:39:07Z
  ... more annotations
```
After executing `mvn package`, I get a .tgz bundle with Chart.yaml like this:
```yaml
annotations:
  build-time: 2023-01-12T12:39:07Z
  ... more annotations
apiVersion: v2
appVersion: 1.0.0-SNAPSHOT
description: My App
name: my-app
version: 1.0.0-SNAPSHOT
```
The property `type` disappeared.
